package com.example.domain

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.net.Uri
import androidx.core.content.FileProvider
import com.example.data.model.PlagiarismMatch
import com.example.data.model.PlagiarismSource
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfReportGenerator {

    suspend fun generateReportPdf(
        context: Context,
        documentName: String,
        wordCount: Int,
        plagiarismPercentage: Int,
        originalPercentage: Int,
        matchedWords: Int,
        sources: List<PlagiarismSource>,
        matches: List<PlagiarismMatch>
    ): File = withContext(Dispatchers.IO) {
        val pdfDocument = PdfDocument()

        val pageWidth = 595 // Standard A4 width in postscript points (72 dpi)
        val pageHeight = 842 // Standard A4 height
        val margin = 40f
        val contentWidth = pageWidth - (margin * 2)

        val titlePaint = Paint().apply {
            color = Color.parseColor("#0F172A")
            textSize = 18f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val subPaint = Paint().apply {
            color = Color.parseColor("#475569")
            textSize = 10f
            typeface = Typeface.DEFAULT
            isAntiAlias = true
        }

        val headerBannerPaint = Paint().apply {
            color = Color.parseColor("#155EEF")
            style = Paint.Style.FILL
            isAntiAlias = true
        }

        val bannerTextPaint = Paint().apply {
            color = Color.WHITE
            textSize = 14f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val sectionTitlePaint = Paint().apply {
            color = Color.parseColor("#155EEF")
            textSize = 12f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val bodyPaint = Paint().apply {
            color = Color.parseColor("#1E293B")
            textSize = 9.5f
            typeface = Typeface.DEFAULT
            isAntiAlias = true
        }

        val boldBodyPaint = Paint().apply {
            color = Color.parseColor("#0F172A")
            textSize = 9.5f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val borderPaint = Paint().apply {
            color = Color.parseColor("#E2E8F0")
            style = Paint.Style.STROKE
            strokeWidth = 1f
            isAntiAlias = true
        }

        val fillCardPaint = Paint().apply {
            color = Color.parseColor("#F8FAFC")
            style = Paint.Style.FILL
            isAntiAlias = true
        }

        val redScorePaint = Paint().apply {
            color = Color.parseColor("#DC2626")
            textSize = 22f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        val greenScorePaint = Paint().apply {
            color = Color.parseColor("#16A34A")
            textSize = 22f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            isAntiAlias = true
        }

        var pageNumber = 1
        var pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
        var page = pdfDocument.startPage(pageInfo)
        var canvas = page.canvas

        fun drawHeader(c: Canvas) {
            c.drawRect(0f, 0f, pageWidth.toFloat(), 48f, headerBannerPaint)
            c.drawText("MUNASAR PLAGIARISM CHECKER", margin, 30f, bannerTextPaint)

            val dateStr = SimpleDateFormat("MMM dd, yyyy HH:mm", Locale.getDefault()).format(Date())
            val dateWidth = subPaint.measureText(dateStr)
            val datePaint = Paint(subPaint).apply { color = Color.WHITE }
            c.drawText(dateStr, pageWidth - margin - dateWidth, 30f, datePaint)
        }

        fun drawFooter(c: Canvas, pageNum: Int) {
            val footerY = pageHeight - 24f
            c.drawLine(margin, footerY - 12f, pageWidth - margin, footerY - 12f, borderPaint)
            val footerText = "Generated by Munasar Plagiarism Checker • https://www.munasar.online/"
            c.drawText(footerText, margin, footerY, subPaint)
            val pageStr = "Page $pageNum"
            val pageStrWidth = subPaint.measureText(pageStr)
            c.drawText(pageStr, pageWidth - margin - pageStrWidth, footerY, subPaint)
        }

        drawHeader(canvas)

        var y = 75f

        // Title and Document Meta
        canvas.drawText("Plagiarism & Originality Audit Report", margin, y, titlePaint)
        y += 18f
        canvas.drawText("Document: $documentName", margin, y, boldBodyPaint)
        y += 14f
        canvas.drawText("Total Words: $wordCount   |   Matched Words: $matchedWords   |   Sources: ${sources.size}", margin, y, subPaint)
        y += 20f

        // Score summary boxes
        val boxWidth = (contentWidth - 16f) / 2f
        val boxHeight = 65f

        // Plagiarism Box
        val plagRect = RectF(margin, y, margin + boxWidth, y + boxHeight)
        canvas.drawRoundRect(plagRect, 6f, 6f, fillCardPaint)
        canvas.drawRoundRect(plagRect, 6f, 6f, borderPaint)

        canvas.drawText("$plagiarismPercentage%", margin + 16f, y + 36f, redScorePaint)
        canvas.drawText("Plagiarism Detected", margin + 16f, y + 52f, subPaint)

        // Originality Box
        val origRect = RectF(margin + boxWidth + 16f, y, margin + (boxWidth * 2) + 16f, y + boxHeight)
        canvas.drawRoundRect(origRect, 6f, 6f, fillCardPaint)
        canvas.drawRoundRect(origRect, 6f, 6f, borderPaint)

        canvas.drawText("$originalPercentage%", margin + boxWidth + 32f, y + 36f, greenScorePaint)
        canvas.drawText("Original Content", margin + boxWidth + 32f, y + 52f, subPaint)

        y += boxHeight + 25f

        // Sources section
        canvas.drawText("DETECTED SOURCES (${sources.size})", margin, y, sectionTitlePaint)
        y += 14f

        if (sources.isEmpty()) {
            canvas.drawText("No duplicate sources detected. Content is 100% original.", margin, y, bodyPaint)
            y += 20f
        } else {
            for (source in sources) {
                if (y > pageHeight - 80f) {
                    drawFooter(canvas, pageNumber)
                    pdfDocument.finishPage(page)
                    pageNumber++
                    pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                    page = pdfDocument.startPage(pageInfo)
                    canvas = page.canvas
                    drawHeader(canvas)
                    y = 70f
                }

                val sourceCard = RectF(margin, y, margin + contentWidth, y + 36f)
                canvas.drawRoundRect(sourceCard, 4f, 4f, fillCardPaint)
                canvas.drawRoundRect(sourceCard, 4f, 4f, borderPaint)

                canvas.drawText(source.title.take(60), margin + 10f, y + 15f, boldBodyPaint)
                canvas.drawText("${source.domain}  •  ${source.matchedWords} words matched (${source.similarity}% match)", margin + 10f, y + 28f, subPaint)
                y += 42f
            }
        }

        y += 15f

        // Matching Passages Section
        if (y > pageHeight - 80f) {
            drawFooter(canvas, pageNumber)
            pdfDocument.finishPage(page)
            pageNumber++
            pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
            page = pdfDocument.startPage(pageInfo)
            canvas = page.canvas
            drawHeader(canvas)
            y = 70f
        }

        canvas.drawText("MATCHING PASSAGES & CITATIONS (${matches.size})", margin, y, sectionTitlePaint)
        y += 16f

        if (matches.isEmpty()) {
            canvas.drawText("No direct sentence matches found in the index.", margin, y, bodyPaint)
            y += 20f
        } else {
            for ((index, match) in matches.withIndex()) {
                val lines = wrapText(match.text, bodyPaint, contentWidth - 20f)
                val cardHeight = 24f + (lines.size * 12f) + 16f

                if (y + cardHeight > pageHeight - 60f) {
                    drawFooter(canvas, pageNumber)
                    pdfDocument.finishPage(page)
                    pageNumber++
                    pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
                    page = pdfDocument.startPage(pageInfo)
                    canvas = page.canvas
                    drawHeader(canvas)
                    y = 70f
                }

                val matchCard = RectF(margin, y, margin + contentWidth, y + cardHeight)
                canvas.drawRoundRect(matchCard, 4f, 4f, fillCardPaint)
                canvas.drawRoundRect(matchCard, 4f, 4f, borderPaint)

                canvas.drawText("Match #${index + 1} (${match.similarity}% similarity) - Source: ${match.sourceTitle ?: "Web Match"}", margin + 10f, y + 14f, boldBodyPaint)

                var textY = y + 28f
                for (line in lines) {
                    canvas.drawText(line, margin + 10f, textY, bodyPaint)
                    textY += 12f
                }

                if (!match.sourceUrl.isNullOrBlank()) {
                    canvas.drawText("URL: ${match.sourceUrl}", margin + 10f, textY + 2f, subPaint)
                }

                y += cardHeight + 8f
            }
        }

        drawFooter(canvas, pageNumber)
        pdfDocument.finishPage(page)

        // Write to output file
        val reportsDir = File(context.cacheDir, "reports")
        if (!reportsDir.exists()) reportsDir.mkdirs()

        val safeDocName = documentName.replace("[^a-zA-Z0-9_.-]".toRegex(), "_")
        val timestamp = System.currentTimeMillis()
        val outputFile = File(reportsDir, "Munasar_Plagiarism_Report_${safeDocName}_$timestamp.pdf")

        FileOutputStream(outputFile).use { out ->
            pdfDocument.writeTo(out)
        }
        pdfDocument.close()

        outputFile
    }

    fun getShareableUri(context: Context, file: File): Uri {
        val authority = "${context.packageName}.fileprovider"
        return FileProvider.getUriForFile(context, authority, file)
    }

    private fun wrapText(text: String, paint: Paint, maxWidth: Float): List<String> {
        val words = text.split(" ")
        val lines = mutableListOf<String>()
        var currentLine = StringBuilder()

        for (word in words) {
            val testLine = if (currentLine.isEmpty()) word else "$currentLine $word"
            if (paint.measureText(testLine) <= maxWidth) {
                currentLine.append(if (currentLine.isEmpty()) word else " $word")
            } else {
                if (currentLine.isNotEmpty()) {
                    lines.add(currentLine.toString())
                }
                currentLine = StringBuilder(word)
            }
        }
        if (currentLine.isNotEmpty()) {
            lines.add(currentLine.toString())
        }
        return lines
    }
}
